default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: careconnect.c9ym0aocyzh5.us-east-2.rds.amazonaws.com
  port: 5432
  database: careconnect_development
  username: CareConnect
  password: Rubypracticum2024!

test:
  <<: *default
  host: careconnect.c9ym0aocyzh5.us-east-2.rds.amazonaws.com
  port: 5432
  database: careconnect_test
  username: CareConnect
  password: Rubypracticum2024!

production:
  <<: *default
  host: careconnect.c9ym0aocyzh5.us-east-2.rds.amazonaws.com
  port: 5432
  database: careconnect_production
  username: CareConnect
  password: Rubypracticum2024!